import { ISubject } from "@/types/index";

const subjects: ISubject[] = [
  {
    _id: "1",
    code: "ESP 8",
    title: "Edukasyon sa Pagpapakatao",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "2",
    code: "Com10",
    title: "Computer",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "3",
    code: "HOSP1007",
    title: "Hotel Fron Ofc Operation Mgt",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "4",
    code: "CITE1003",
    title: "Computer Programming 1",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "5",
    code: "SPECIAL1068",
    title: "Pre-Calculus",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "6",
    code: "CORE1011",
    title: "Pagbasa at Pagsusuri",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "7",
    code: "APPLIED1014",
    title: "Practical Research 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "8",
    code: "HOSP1024",
    title: "Specialty Cuisine  w/ Food Exh",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "4",
    semester: "1st Semester",
  },
];

export function getSubjectStore() {
  return subjects;
}
